# Generated by Django 2.2.6 on 2019-11-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Person.PersonDetails'),
            preserve_default=False,
        ),
    ]
